Vertex:
	./glslc main.vert -o vert.spv
Fragment:
	./glslc test.frag -o frag.spv
shadowMapfrag:
	./glslc sm.frag -o smfrag.spv
shadowMapvert:
	./glslc sm.vert -o smvert.spv
reflectionfrag:
	./glslc reflection.frag -o rfrag.spv
reflectionvert:
	./glslc reflection.vert -o rvert.spv
postfrag:
	./glslc Post.frag -o pfrag.spv
postvert:
	./glslc Post.vert -o pvert.spv